@echo off
start "" /MAX "C:\Users\Public\Desktop\VMQuickConfig"
python -c "import pyautogui as pag; pag.click(143, 487, duration=5)"
python -c "import pyautogui as pag; pag.click(155, 554, duration=2)"
python -c "import pyautogui as pag; pag.click(637, 417, duration=2)"
python -c "import pyautogui as pag; pag.click(588, 10, duration=2)"
echo ..........................................................
echo .....Modified By The UnclelUO.............................
echo ..........................................................
echo ..........................................................
echo ......... Telegram Channel - https://t.me/Uncleluogroup...
echo ..........................................................
echo ..Youtube Channel - https://www.youtube.com/@UncleLuo.....
echo ..........................................................
echo Your Device Name: %username%@%computername%
echo User Name: runneradmin
echo User Pass: UncleLu0
